import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const pluginDir = path.join(__dirname, 'p2p-sync-demo-vault', '.obsidian', 'plugins', 'obsidian-p2p-sync');

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
};

// Copy WASM file to the build directory
fs.copyFileSync(
	path.join(__dirname, 'pkg', 'obsidian_p2p_sync_bg.wasm'),
	path.join(pluginDir, 'obsidian_p2p_sync_bg.wasm')
);
console.log('Copied obsidian_p2p_sync_bg.wasm to plugin directory');

// Create an esbuild context so we can use watch/rebuild in a version-compatible way
const context = await esbuild.context(buildOptions);

if (prod) {
	await context.rebuild();
	// Copy to demo vault plugin folder
	try {
		if (!fs.existsSync(pluginDir)) {
			fs.mkdirSync(pluginDir, { recursive: true });
		}
		fs.copyFileSync('main.js', path.join(pluginDir, 'main.js'));
		fs.copyFileSync('manifest.json', path.join(pluginDir, 'manifest.json'));
		if (fs.existsSync('main.css')) {
			fs.copyFileSync('main.css', path.join(pluginDir, 'styles.css'));
		}
		// Copy WASM files if they exist
		if (fs.existsSync('pkg')) {
			const pkgDir = path.join(pluginDir, 'pkg');
			if (!fs.existsSync(pkgDir)) {
				fs.mkdirSync(pkgDir, { recursive: true });
			}
			const wasmFiles = fs.readdirSync('pkg');
			wasmFiles.forEach(file => {
				fs.copyFileSync(
					path.join('pkg', file),
					path.join(pkgDir, file)
				);
			});
		}
		console.log(`✓ Plugin built and copied to demo vault`);
	} catch (err) {
		console.warn(`Note: Could not copy to demo vault (${err.message}). Plugin folder may not exist yet.`);
	}
	process.exit(0);
} else {
	// Start watch using context.watch() (no options supported in this esbuild version)
	await context.watch();

	// Debounced file copy helper
	let copyTimeout = null;
	const scheduleCopy = () => {
		if (copyTimeout) clearTimeout(copyTimeout);
		copyTimeout = setTimeout(() => {
			try {
				if (fs.existsSync(pluginDir)) {
					fs.copyFileSync('main.js', path.join(pluginDir, 'main.js'));
					if (fs.existsSync('main.css')) {
						fs.copyFileSync('main.css', path.join(pluginDir, 'styles.css'));
					}
					if (fs.existsSync('pkg')) {
						const pkgDir = path.join(pluginDir, 'pkg');
						if (!fs.existsSync(pkgDir)) {
							fs.mkdirSync(pkgDir, { recursive: true });
						}
						const wasmFiles = fs.readdirSync('pkg');
						wasmFiles.forEach(file => {
							fs.copyFileSync(
								path.join('pkg', file),
								path.join(pkgDir, file)
							);
						});
					}
					console.log(`✓ Plugin copied to demo vault (watching for changes...)`);
				}
			} catch (err) {
				// Silently ignore copy errors in watch mode
			}
		}, 200);
	};

	// Initial copy
	scheduleCopy();

	// Watch output files/directories for changes and trigger copy
	try {
		// Watch main.js
		fs.watchFile('main.js', { interval: 200 }, (curr, prev) => {
			if (curr.mtimeMs !== prev.mtimeMs) scheduleCopy();
		});

		// Watch pkg directory if it exists, fallback to polling for its creation
		const watchPkg = () => {
			if (fs.existsSync('pkg')) {
				fs.watch('pkg', (eventType, filename) => {
					scheduleCopy();
				});
			} else {
				// Poll for directory creation
				setTimeout(watchPkg, 500);
			}
		};
		watchPkg();
	} catch (err) {
		// Ignore watch errors
	}
}
