/**
 * WASM Integration Module
 * Handles loading and managing the Rust WASM module
 */

import { WasmModule, P2PNodeInstance } from './types';
import { Notice } from 'obsidian';

export class WasmBridge {
  private wasmModule: WasmModule | null = null;
  private p2pNode: P2PNodeInstance | null = null;
  private isInitialized = false;

  /**
   * Initialize the WASM module
   */
  async initialize(wasmBuffer: ArrayBuffer | Uint8Array): Promise<boolean> {
    try {
      if (this.isInitialized && this.wasmModule) {
        console.log('WASM module already initialized');
        return true;
      }

      // Import the WASM module glue (generated by wasm-bindgen)
      // @ts-ignore - WASM module is dynamically generated
      const mod = await import('../pkg/obsidian_p2p_sync.js');

      // Initialize the underlying wasm binary so `wasm` exports are set.
      try {
        const initFn = (mod && (mod.default || mod)) as any;
        if (typeof initFn === 'function') {
          // Initialize with the provided ArrayBuffer
          await initFn(wasmBuffer);
        }
      } catch (e) {
        console.error('WASM initialization (glue) failed:', e);
        throw e;
      }

      // Accept the module even if types don't match perfectly
      this.wasmModule = mod as unknown as WasmModule;
      this.isInitialized = true;

      console.log('WASM module initialized successfully');
      console.log('Version:', this.getVersion());

      return true;
    } catch (error) {
      console.error('Failed to initialize WASM module:', error);
      new Notice('Warning: P2P module not available. Please rebuild: npm run build:wasm');
      return false;
    }
  }

  /**
   * Get the WASM module instance
   */
  getModule(): WasmModule | null {
    return this.wasmModule;
  }

  /**
   * Get the P2P node instance
   */
  getNode(): P2PNodeInstance | null {
    return this.p2pNode;
  }

  /**
   * Create or get the P2P node
   */
  createOrGetNode(deviceName: string, deviceId: string): P2PNodeInstance | null {
    if (!this.wasmModule) {
      console.error('WASM module not initialized');
      return null;
    }

    if (!this.p2pNode) {
      try {
        this.p2pNode = new this.wasmModule.P2PNode(deviceName, deviceId);
        console.log('P2P node created:', deviceName, deviceId);
      } catch (error) {
        console.error('Failed to create P2P node:', error);
        return null;
      }
    }

    return this.p2pNode;
  }

  /**
   * Get version from WASM module
   */
  getVersion(): string {
    if (!this.wasmModule) {
      return 'unknown';
    }

    try {
      return this.wasmModule.get_version();
    } catch (error) {
      console.error('Failed to get version:', error);
      return 'unknown';
    }
  }

  /**
   * Test Rust integration
   */
  testIntegration(name: string): string {
    if (!this.wasmModule) {
      return 'WASM module not initialized';
    }

    try {
      return this.wasmModule.greet_from_rust(name);
    } catch (error) {
      console.error('Test failed:', error);
      return 'Test failed';
    }
  }

  /**
   * Cleanup WASM resources
   */
  cleanup(): void {
    if (this.p2pNode) {
      try {
        this.p2pNode.free?.();
      } catch (error) {
        console.warn('Error freeing P2P node:', error);
      }
      this.p2pNode = null;
    }

    this.isInitialized = false;
  }
}
